name: Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
      
      - name: Install dependencies
        shell: bash
        run: npm ci

      - name: Build
        shell: bash
        run: npm run build

      # Get tag to use, create it if it doesn't exist, create changelog, create release, upload artifacts (dist/** and README.md), and notify discord
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1

      - name: Create tag
        if: steps.version.outputs.tag == ''
        shell: bash
        run: git tag ${{ steps.version.outputs.version }}
      
      - name: Create changelog
        if: steps.version.outputs.tag == ''
        shell: bash
        run: |
          git config --global user.email "
          git config --global user.name "GitHub Actions"
          git log --pretty=format:"%s" --reverse ${{ steps.version.outputs.previous_version }}..${{ steps.version.outputs.version }} > CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "chore: update changelog"
          git push
      
      - name: Create release
        if: steps.version.outputs.tag == ''
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**
            README.md
          name: ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload build artifacts
        if: steps.version.outputs.tag == ''
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
          retention-days: 1
      
      - name: Upload README.md
        if: steps.version.outputs.tag == ''
        uses: actions/upload-artifact@v2
        with:
          name: README.md
          path: README.md
          retention-days: 1
      
      - name: Notify Discord
        if: steps.version.outputs.tag == ''
        uses: Ilshidur/action-discord@v3
        with:
          args: "New release ${{ steps.version.outputs.version }} is available! Check it out Actions"

      
