name: Build

on:
  workflow_dispatch:

  push:
    branches:
      - master
    tags:
      - v*

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make directory for build files
        shell: bash
        run: mkdir dist
      
      - name: Create bogus file
        shell: bash
        run: echo "This is a bogus file" > dist/bogus.txt

      - name: Get version
        id: version
        uses: codacy/git-version@2.7.1
      
      - name: Compress build files
        shell: bash
        run: |
          sudo apt install zip -y
          cd dist
          tar -czvf ../release-${{ steps.version.outputs.version }}.tar.gz *
          zip -r ../release-${{ steps.version.outputs.version }}.zip *

      - name: Create tag ${{ steps.version.outputs.version }}
        shell: bash
        run: git tag ${{ steps.version.outputs.version }}
      
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3.6.0
      
      - name: Create CHANGELOG.md
        shell: bash
        run: echo "${{ steps.build_changelog.outputs.changelog }}" > CHANGELOG.md
      
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-${{ steps.version.outputs.version }}.tar.gz
            release-${{ steps.version.outputs.version }}.zip
          name: ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
