name: Build

on:
  workflow_dispatch:

  push:
    branches:
      - master
    tags:
      - v*

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make directory for build files
        shell: bash
        run: mkdir dist
      
      - name: Create bogus file
        shell: bash
        run: echo "This is a bogus file" > dist/bogus.txt
      
      - name: Compress build files
        shell: bash
        run: |
          sudo apt install zip -y
          cd dist
          tar -czvf ../release-$VERSION.tar.gz *
          zip -r ../release-$VERSION.zip *

      - name: Get version
        id: version
        uses: codacy/git-version@2.7.1
      
      - name: Set environment variables
        shell: bash
        run: |
          echo "VERSION=${{ steps.version.outputs.version }}" >> $GITHUB_ENV
          echo "PREVIOUS_VERSION=${{ steps.version.outputs.previous_version }}" >> $GITHUB_ENV

      - name: Create tag
        shell: bash
        run: git tag $VERSION
      
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3.6.0
      
      - name: Create CHANGELOG.md
        shell: bash
        run: |
          echo "${{ steps.build_changelog.outputs.changelog }}" > CHANGELOG.md
          cat CHANGELOG.md
      
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-$VERSION.tar.gz
            release-$VERSION.zip
          name: $VERSION
          tag_name: $VERSION
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
