name: Build

on:
  workflow_dispatch:

  push:
    branches:
      - master
    tags:
      - v*

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get version
        id: version
        uses: codacy/git-version@2.7.1
      
      - name: Set environment variables
        shell: bash
        run: |
          echo "VERSION=${{ steps.version.outputs.version }}" >> $GITHUB_ENV
          echo "ARCHIVE_NAME=release-${{ steps.version.outputs.version }}" >> $GITHUB_ENV

      - name: Initialize
        shell: bash
        run: mkdir dist
      
      - name: Build
        shell: bash
        run: echo "This is a bogus file" > dist/bogus.txt

      - name: Compress build artifacts
        shell: bash
        run: |
          sudo apt install zip -y
          cd dist
          tar -czvf ../${{ env.ARCHIVE_NAME }}.tar.gz *
          zip -r ../${{ env.ARCHIVE_NAME }}.zip *
       
      - name: Create tag
        shell: bash
        run: git tag ${{ env.VERSION }}
      
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3.6.0
        with:
          configuration: ../changelog-config.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ARCHIVE_NAME }}.tar.gz
            ${{ env.ARCHIVE_NAME }}.zip
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
