name: Build

on:
  workflow_dispatch:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
      
      - name: Install dependencies
        shell: bash
        run: npm ci

      - name: Build
        shell: bash
        run: npm run build

      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}